name: Java CI with Maven and MongoDB

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  test:
    name: Unit Test
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand(\"ping\").ok'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Wait for MongoDB to be ready

        run: |
          for i in seq 1 10; do
            nc -z localhost 27017 && echo "MongoDB is ready" && break
            echo "Waiting for MongoDB to start..."
            sleep 5
          done

      - name: Maven Package (without tests, if you prefer to run tests separately)
        run: mvn -B clean package -DskipTests

      - name: Maven Verify (Run tests)
        run: mvn -B verify
        env:
          MONGODB_URI: "mongodb://localhost:27017/your_test_database"
